# Generated by Django 3.0.6 on 2020-05-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preserial_stock', '0002_auto_20200510_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='finalproductnumber',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Assembly number'),
        ),
    ]
