# Generated by Django 3.0.6 on 2020-05-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preserial_stock', '0003_auto_20200524_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleproductsnumber',
            name='gs',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='singleproductsnumber',
            name='receive_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='singleproductsnumber',
            name='stock',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='singleproductsnumber',
            name='tool_maker',
            field=models.CharField(max_length=100, null=True, verbose_name='Tool maker'),
        ),
    ]
